// Duizend dataset — v1, items 1-300 of the first 1000
// w=Dutch word/chunk, s=Dutch sentence, e=English gloss, v=Swedish gloss,
// x=English sentence (production prompt), t=theme(core/life/fam), c=cognate with Swedish
const WORDS=[
{i:1,w:"hallo",s:"Hallo, hoe gaat het?",e:"hello",v:"hej",x:"Hello, how are you?",t:"core",c:1},
{i:2,w:"ja",s:"Ja, dat is goed.",e:"yes",v:"ja",x:"Yes, that is good.",t:"core",c:1},
{i:3,w:"nee",s:"Nee, dank je.",e:"no",v:"nej",x:"No, thank you.",t:"core",c:1},
{i:4,w:"dank je wel",s:"Dank je wel voor de koffie.",e:"thank you",v:"tack så mycket",x:"Thank you for the coffee.",t:"core",c:0},
{i:5,w:"alsjeblieft",s:"Een biertje, alsjeblieft.",e:"please / here you go",v:"tack / varsågod",x:"A beer, please.",t:"core",c:0},
{i:6,w:"ik",s:"Ik woon in Amsterdam.",e:"I",v:"jag",x:"I live in Amsterdam.",t:"core",c:0},
{i:7,w:"jij",s:"Jij bent lief.",e:"you",v:"du",x:"You are sweet.",t:"core",c:0},
{i:8,w:"hij",s:"Hij is mijn vriend.",e:"he",v:"han",x:"He is my boyfriend.",t:"fam",c:0},
{i:9,w:"zij",s:"Zij komt uit Zweden.",e:"she",v:"hon",x:"She comes from Sweden.",t:"core",c:0},
{i:10,w:"wij",s:"Wij gaan naar de stad.",e:"we",v:"vi",x:"We are going to the city.",t:"core",c:1},
{i:11,w:"zijn",s:"Ze zijn thuis.",e:"to be",v:"att vara",x:"They are at home.",t:"core",c:0},
{i:12,w:"hebben",s:"Wij hebben een kat.",e:"to have",v:"att ha",x:"We have a cat.",t:"core",c:1},
{i:13,w:"gaan",s:"We gaan morgen naar de markt.",e:"to go",v:"att gå",x:"We are going to the market tomorrow.",t:"core",c:1},
{i:14,w:"komen",s:"Kom je vanavond?",e:"to come",v:"att komma",x:"Are you coming tonight?",t:"core",c:1},
{i:15,w:"doen",s:"Wat doe je vandaag?",e:"to do",v:"att göra",x:"What are you doing today?",t:"core",c:0},
{i:16,w:"willen",s:"Ik wil graag een koffie.",e:"to want",v:"att vilja",x:"I would like a coffee.",t:"core",c:1},
{i:17,w:"kunnen",s:"Kun je dat herhalen?",e:"can / to be able",v:"att kunna",x:"Can you repeat that?",t:"core",c:1},
{i:18,w:"moeten",s:"Ik moet nu werken.",e:"must / to have to",v:"att behöva / måste",x:"I have to work now.",t:"core",c:0},
{i:19,w:"weten",s:"Ik weet het niet.",e:"to know",v:"att veta",x:"I don't know.",t:"core",c:1},
{i:20,w:"zien",s:"Tot ziens, ik zie je morgen!",e:"to see",v:"att se",x:"Goodbye, I'll see you tomorrow!",t:"core",c:1},
{i:21,w:"wat",s:"Wat is dat?",e:"what",v:"vad",x:"What is that?",t:"core",c:1},
{i:22,w:"wie",s:"Wie is dat?",e:"who",v:"vem",x:"Who is that?",t:"core",c:0},
{i:23,w:"waar",s:"Waar is het station?",e:"where",v:"var",x:"Where is the station?",t:"life",c:1},
{i:24,w:"wanneer",s:"Wanneer begint de film?",e:"when",v:"när",x:"When does the movie start?",t:"core",c:0},
{i:25,w:"waarom",s:"Waarom lach je?",e:"why",v:"varför",x:"Why are you laughing?",t:"core",c:1},
{i:26,w:"hoe",s:"Hoe heet je?",e:"how",v:"hur",x:"What is your name?",t:"core",c:1},
{i:27,w:"hoeveel",s:"Hoeveel kost dit?",e:"how much",v:"hur mycket",x:"How much does this cost?",t:"life",c:0},
{i:28,w:"goedemorgen",s:"Goedemorgen, lekker geslapen?",e:"good morning",v:"god morgon",x:"Good morning, did you sleep well?",t:"fam",c:1},
{i:29,w:"goedenavond",s:"Goedenavond allemaal!",e:"good evening",v:"god kväll",x:"Good evening everyone!",t:"core",c:0},
{i:30,w:"tot ziens",s:"Tot ziens en bedankt!",e:"goodbye",v:"vi ses / hej då",x:"Goodbye and thanks!",t:"core",c:0},
{i:31,w:"doei",s:"Doei, tot morgen!",e:"bye (informal)",v:"hej då",x:"Bye, see you tomorrow!",t:"core",c:0},
{i:32,w:"sorry",s:"Sorry, ik ben te laat.",e:"sorry",v:"förlåt",x:"Sorry, I am late.",t:"core",c:0},
{i:33,w:"pardon",s:"Pardon, mag ik erlangs?",e:"excuse me",v:"ursäkta",x:"Excuse me, may I pass?",t:"life",c:0},
{i:34,w:"lekker",s:"Het eten is echt lekker.",e:"tasty / nice",v:"god / skön",x:"The food is really tasty.",t:"core",c:0},
{i:35,w:"gezellig",s:"Wat een gezellige avond!",e:"cozy / fun (untranslatable)",v:"mysig / trevlig",x:"What a cozy evening!",t:"fam",c:0},
{i:36,w:"mooi",s:"Wat een mooi huis!",e:"beautiful",v:"vacker / fin",x:"What a beautiful house!",t:"core",c:0},
{i:37,w:"goed",s:"Het gaat goed met mij.",e:"good",v:"bra / god",x:"I am doing well.",t:"core",c:1},
{i:38,w:"slecht",s:"Het weer is slecht vandaag.",e:"bad",v:"dålig",x:"The weather is bad today.",t:"core",c:0},
{i:39,w:"groot",s:"Amsterdam is een grote stad.",e:"big",v:"stor",x:"Amsterdam is a big city.",t:"core",c:0},
{i:40,w:"klein",s:"We hebben een klein appartement.",e:"small",v:"liten",x:"We have a small apartment.",t:"life",c:0},
{i:41,w:"nieuw",s:"Is dat een nieuwe fiets?",e:"new",v:"ny",x:"Is that a new bike?",t:"core",c:1},
{i:42,w:"oud",s:"Dit is een oude kerk.",e:"old",v:"gammal",x:"This is an old church.",t:"core",c:0},
{i:43,w:"het huis",s:"Ons huis staat aan de gracht.",e:"the house",v:"huset",x:"Our house is on the canal.",t:"life",c:1},
{i:44,w:"de gracht",s:"We wandelen langs de gracht.",e:"the canal",v:"kanalen",x:"We walk along the canal.",t:"life",c:0},
{i:45,w:"de fiets",s:"Mijn fiets is gestolen.",e:"the bicycle",v:"cykeln",x:"My bike was stolen.",t:"life",c:0},
{i:46,w:"de stad",s:"Ik ga naar de stad.",e:"the city",v:"staden",x:"I am going to the city.",t:"life",c:1},
{i:47,w:"de straat",s:"In welke straat woon je?",e:"the street",v:"gatan",x:"On which street do you live?",t:"life",c:0},
{i:48,w:"het water",s:"Mag ik een glas water?",e:"the water",v:"vattnet",x:"May I have a glass of water?",t:"core",c:1},
{i:49,w:"de koffie",s:"Zullen we koffie drinken?",e:"the coffee",v:"kaffet",x:"Shall we drink coffee?",t:"life",c:1},
{i:50,w:"het bier",s:"Twee bier, alsjeblieft.",e:"the beer",v:"ölen",x:"Two beers, please.",t:"life",c:0},
{i:51,w:"de thee",s:"Wil je thee of koffie?",e:"the tea",v:"teet",x:"Do you want tea or coffee?",t:"core",c:1},
{i:52,w:"het brood",s:"Ik koop vers brood bij de bakker.",e:"the bread",v:"brödet",x:"I buy fresh bread at the bakery.",t:"life",c:1},
{i:53,w:"de kaas",s:"Nederlandse kaas is beroemd.",e:"the cheese",v:"osten",x:"Dutch cheese is famous.",t:"life",c:0},
{i:54,w:"de melk",s:"De melk staat in de koelkast.",e:"the milk",v:"mjölken",x:"The milk is in the fridge.",t:"life",c:1},
{i:55,w:"eten",s:"Wat eten we vanavond?",e:"to eat",v:"att äta",x:"What are we eating tonight?",t:"fam",c:1},
{i:56,w:"drinken",s:"Wil je iets drinken?",e:"to drink",v:"att dricka",x:"Do you want something to drink?",t:"core",c:1},
{i:57,w:"het ontbijt",s:"Ik maak het ontbijt klaar.",e:"the breakfast",v:"frukosten",x:"I am preparing breakfast.",t:"fam",c:0},
{i:58,w:"het avondeten",s:"Het avondeten is klaar!",e:"the dinner",v:"middagen",x:"Dinner is ready!",t:"fam",c:0},
{i:59,w:"de boodschappen",s:"Ik ga boodschappen doen.",e:"the groceries",v:"matvarorna",x:"I am going grocery shopping.",t:"life",c:0},
{i:60,w:"de markt",s:"Op zaterdag gaan we naar de markt.",e:"the market",v:"marknaden",x:"On Saturday we go to the market.",t:"life",c:1},
{i:61,w:"de winkel",s:"De winkel is om zes uur dicht.",e:"the shop",v:"affären / butiken",x:"The shop closes at six o'clock.",t:"life",c:0},
{i:62,w:"kopen",s:"Ik wil bloemen kopen.",e:"to buy",v:"att köpa",x:"I want to buy flowers.",t:"life",c:1},
{i:63,w:"betalen",s:"Kan ik met pin betalen?",e:"to pay",v:"att betala",x:"Can I pay by card?",t:"life",c:1},
{i:64,w:"kosten",s:"Wat kost een kilo appels?",e:"to cost",v:"att kosta",x:"How much does a kilo of apples cost?",t:"life",c:1},
{i:65,w:"duur",s:"Amsterdam is erg duur.",e:"expensive",v:"dyr",x:"Amsterdam is very expensive.",t:"life",c:1},
{i:66,w:"goedkoop",s:"Deze appels zijn goedkoop.",e:"cheap",v:"billig",x:"These apples are cheap.",t:"life",c:0},
{i:67,w:"het geld",s:"Ik heb geen geld bij me.",e:"the money",v:"pengarna",x:"I have no money with me.",t:"core",c:0},
{i:68,w:"vandaag",s:"Vandaag is het maandag.",e:"today",v:"idag",x:"Today is Monday.",t:"core",c:1},
{i:69,w:"morgen",s:"Morgen ga ik naar mijn werk.",e:"tomorrow",v:"imorgon",x:"Tomorrow I am going to work.",t:"core",c:1},
{i:70,w:"gisteren",s:"Gisteren was het mooi weer.",e:"yesterday",v:"igår",x:"Yesterday the weather was nice.",t:"core",c:0},
{i:71,w:"nu",s:"Ik moet nu gaan.",e:"now",v:"nu",x:"I have to go now.",t:"core",c:1},
{i:72,w:"straks",s:"Tot straks!",e:"later (today)",v:"strax / snart",x:"See you later!",t:"fam",c:1},
{i:73,w:"altijd",s:"Jij bent altijd te laat!",e:"always",v:"alltid",x:"You are always late!",t:"fam",c:1},
{i:74,w:"nooit",s:"Ik drink nooit koffie na acht uur.",e:"never",v:"aldrig",x:"I never drink coffee after eight o'clock.",t:"core",c:0},
{i:75,w:"vaak",s:"We gaan vaak naar het park.",e:"often",v:"ofta",x:"We often go to the park.",t:"core",c:0},
{i:76,w:"soms",s:"Soms mis ik Zweden.",e:"sometimes",v:"ibland",x:"Sometimes I miss Sweden.",t:"fam",c:0},
{i:77,w:"de dag",s:"Fijne dag nog!",e:"the day",v:"dagen",x:"Have a nice day!",t:"core",c:1},
{i:78,w:"de week",s:"Volgende week heb ik vrij.",e:"the week",v:"veckan",x:"Next week I am off.",t:"core",c:1},
{i:79,w:"het weekend",s:"Wat doen we dit weekend?",e:"the weekend",v:"helgen",x:"What are we doing this weekend?",t:"fam",c:0},
{i:80,w:"het jaar",s:"Ik woon hier al een jaar.",e:"the year",v:"året",x:"I have lived here for a year already.",t:"core",c:0},
{i:81,w:"de tijd",s:"Heb je tijd voor een kopje koffie?",e:"the time",v:"tiden",x:"Do you have time for a cup of coffee?",t:"core",c:1},
{i:82,w:"het uur",s:"De les duurt een uur.",e:"the hour",v:"timmen",x:"The lesson lasts one hour.",t:"core",c:0},
{i:83,w:"laat",s:"Hoe laat is het?",e:"late / what time",v:"sen",x:"What time is it?",t:"core",c:0},
{i:84,w:"vroeg",s:"Ik sta vroeg op.",e:"early",v:"tidig",x:"I get up early.",t:"core",c:0},
{i:85,w:"het werk",s:"Ik ga met de fiets naar het werk.",e:"the work",v:"jobbet",x:"I go to work by bike.",t:"life",c:0},
{i:86,w:"werken",s:"Mijn vriend werkt in Utrecht.",e:"to work",v:"att arbeta / jobba",x:"My boyfriend works in Utrecht.",t:"fam",c:0},
{i:87,w:"wonen",s:"Waar woon jij?",e:"to live (reside)",v:"att bo",x:"Where do you live?",t:"core",c:0},
{i:88,w:"slapen",s:"Ik ga slapen, welterusten!",e:"to sleep",v:"att sova",x:"I am going to sleep, good night!",t:"fam",c:0},
{i:89,w:"welterusten",s:"Welterusten, slaap lekker.",e:"good night",v:"god natt",x:"Good night, sleep well.",t:"fam",c:0},
{i:90,w:"opstaan",s:"Ik sta om zeven uur op.",e:"to get up",v:"att stiga upp",x:"I get up at seven o'clock.",t:"core",c:1},
{i:91,w:"de trein",s:"De trein naar Utrecht is vertraagd.",e:"the train",v:"tåget",x:"The train to Utrecht is delayed.",t:"life",c:0},
{i:92,w:"de tram",s:"Welke tram gaat naar het Centraal Station?",e:"the tram",v:"spårvagnen",x:"Which tram goes to Central Station?",t:"life",c:0},
{i:93,w:"de bus",s:"De bus komt over vijf minuten.",e:"the bus",v:"bussen",x:"The bus comes in five minutes.",t:"life",c:1},
{i:94,w:"het station",s:"Ik wacht op het station.",e:"the station",v:"stationen",x:"I am waiting at the station.",t:"life",c:1},
{i:95,w:"de halte",s:"Dit is mijn halte.",e:"the stop",v:"hållplatsen",x:"This is my stop.",t:"life",c:0},
{i:96,w:"reizen",s:"Ik reis graag met de trein.",e:"to travel",v:"att resa",x:"I like traveling by train.",t:"life",c:1},
{i:97,w:"fietsen",s:"In Amsterdam fietst iedereen.",e:"to cycle",v:"att cykla",x:"In Amsterdam everyone cycles.",t:"life",c:1},
{i:98,w:"lopen",s:"We lopen naar het park.",e:"to walk",v:"att gå / promenera",x:"We are walking to the park.",t:"core",c:0},
{i:99,w:"rechts",s:"Bij de brug ga je naar rechts.",e:"right",v:"höger",x:"At the bridge you go right.",t:"life",c:0},
{i:100,w:"links",s:"De supermarkt is aan de linkerkant.",e:"left",v:"vänster",x:"The supermarket is on the left side.",t:"life",c:0},
{i:101,w:"rechtdoor",s:"Ga rechtdoor tot het stoplicht.",e:"straight ahead",v:"rakt fram",x:"Go straight ahead until the traffic light.",t:"life",c:0},
{i:102,w:"de brug",s:"We staan op de brug.",e:"the bridge",v:"bron",x:"We are standing on the bridge.",t:"life",c:0},
{i:103,w:"dichtbij",s:"Het café is dichtbij.",e:"nearby",v:"nära",x:"The café is nearby.",t:"life",c:0},
{i:104,w:"ver",s:"Is het ver lopen?",e:"far",v:"långt",x:"Is it far to walk?",t:"life",c:0},
{i:105,w:"hier",s:"Kom hier zitten.",e:"here",v:"här",x:"Come sit here.",t:"core",c:1},
{i:106,w:"daar",s:"Daar is de ingang.",e:"there",v:"där",x:"There is the entrance.",t:"core",c:1},
{i:107,w:"de vriend",s:"Dit is mijn vriend Daan.",e:"the boyfriend / friend",v:"pojkvännen / vännen",x:"This is my boyfriend Daan.",t:"fam",c:1},
{i:108,w:"de vriendin",s:"Mijn vriendin komt uit Zweden.",e:"the girlfriend / friend (f)",v:"flickvännen / väninnan",x:"My girlfriend comes from Sweden.",t:"fam",c:1},
{i:109,w:"de moeder",s:"Zijn moeder kookt heel goed.",e:"the mother",v:"mamman / modern",x:"His mother cooks very well.",t:"fam",c:1},
{i:110,w:"de vader",s:"Zijn vader houdt van voetbal.",e:"the father",v:"pappan / fadern",x:"His father loves football.",t:"fam",c:1},
{i:111,w:"de ouders",s:"We eten zondag bij zijn ouders.",e:"the parents",v:"föräldrarna",x:"On Sunday we eat at his parents' place.",t:"fam",c:0},
{i:112,w:"de broer",s:"Zijn broer woont in Rotterdam.",e:"the brother",v:"brodern",x:"His brother lives in Rotterdam.",t:"fam",c:1},
{i:113,w:"de zus",s:"Mijn zus komt op bezoek.",e:"the sister",v:"systern",x:"My sister is coming to visit.",t:"fam",c:0},
{i:114,w:"de familie",s:"Zijn familie is heel gezellig.",e:"the family",v:"familjen",x:"His family is very fun to be with.",t:"fam",c:1},
{i:115,w:"de oma",s:"Oma maakt de beste appeltaart.",e:"the grandma",v:"mormor / farmor",x:"Grandma makes the best apple pie.",t:"fam",c:0},
{i:116,w:"de opa",s:"Opa vertelt altijd verhalen.",e:"the grandpa",v:"morfar / farfar",x:"Grandpa always tells stories.",t:"fam",c:0},
{i:117,w:"houden van",s:"Ik hou van jou.",e:"to love",v:"att älska",x:"I love you.",t:"fam",c:0},
{i:118,w:"lief",s:"Wat lief van je!",e:"sweet / kind",v:"gullig / snäll",x:"How sweet of you!",t:"fam",c:0},
{i:119,w:"de schat",s:"Schat, waar zijn de sleutels?",e:"darling / treasure",v:"älskling / skatten",x:"Darling, where are the keys?",t:"fam",c:1},
{i:120,w:"samen",s:"We koken vanavond samen.",e:"together",v:"tillsammans",x:"We are cooking together tonight.",t:"fam",c:1},
{i:121,w:"de kus",s:"Geef me een kus.",e:"the kiss",v:"kyssen / pussen",x:"Give me a kiss.",t:"fam",c:1},
{i:122,w:"missen",s:"Ik mis mijn familie in Zweden.",e:"to miss",v:"att sakna",x:"I miss my family in Sweden.",t:"fam",c:1},
{i:123,w:"blij",s:"Ik ben zo blij met jou.",e:"happy / glad",v:"glad",x:"I am so happy with you.",t:"fam",c:1},
{i:124,w:"verdrietig",s:"Waarom ben je verdrietig?",e:"sad",v:"ledsen",x:"Why are you sad?",t:"fam",c:0},
{i:125,w:"moe",s:"Ik ben moe na het werk.",e:"tired",v:"trött",x:"I am tired after work.",t:"core",c:0},
{i:126,w:"ziek",s:"Ik ben ziek, ik blijf thuis.",e:"sick",v:"sjuk",x:"I am sick, I am staying home.",t:"core",c:1},
{i:127,w:"honger hebben",s:"Ik heb honger, en jij?",e:"to be hungry",v:"att vara hungrig",x:"I am hungry, and you?",t:"core",c:1},
{i:128,w:"dorst hebben",s:"Ik heb dorst na het fietsen.",e:"to be thirsty",v:"att vara törstig",x:"I am thirsty after cycling.",t:"core",c:1},
{i:129,w:"zin hebben in",s:"Ik heb zin in pizza.",e:"to feel like / crave",v:"att vara sugen på",x:"I feel like pizza.",t:"fam",c:0},
{i:130,w:"het weer",s:"Het weer is vandaag prachtig.",e:"the weather",v:"vädret",x:"The weather is gorgeous today.",t:"life",c:1},
{i:131,w:"de regen",s:"We blijven binnen vanwege de regen.",e:"the rain",v:"regnet",x:"We are staying inside because of the rain.",t:"life",c:1},
{i:132,w:"regenen",s:"Het regent alweer.",e:"to rain",v:"att regna",x:"It is raining again.",t:"life",c:1},
{i:133,w:"de zon",s:"De zon schijnt eindelijk!",e:"the sun",v:"solen",x:"The sun is finally shining!",t:"life",c:1},
{i:134,w:"de wind",s:"Fietsen met tegenwind is zwaar.",e:"the wind",v:"vinden",x:"Cycling against the wind is hard.",t:"life",c:1},
{i:135,w:"koud",s:"Het is koud buiten.",e:"cold",v:"kall",x:"It is cold outside.",t:"core",c:1},
{i:136,w:"warm",s:"Het is warm in de zomer.",e:"warm",v:"varm",x:"It is warm in the summer.",t:"core",c:1},
{i:137,w:"binnen",s:"We eten binnen, het is te koud.",e:"inside",v:"inne / inomhus",x:"We are eating inside, it is too cold.",t:"core",c:0},
{i:138,w:"buiten",s:"De kinderen spelen buiten.",e:"outside",v:"ute / utomhus",x:"The children are playing outside.",t:"core",c:0},
{i:139,w:"een",s:"Ik neem een broodje.",e:"one / a",v:"en / ett",x:"I'll take a sandwich.",t:"core",c:1},
{i:140,w:"twee",s:"Twee kaartjes, alsjeblieft.",e:"two",v:"två",x:"Two tickets, please.",t:"core",c:1},
{i:141,w:"drie",s:"We zijn met drie personen.",e:"three",v:"tre",x:"We are three people.",t:"core",c:1},
{i:142,w:"vier",s:"De trein vertrekt om vier uur.",e:"four",v:"fyra",x:"The train leaves at four o'clock.",t:"core",c:1},
{i:143,w:"vijf",s:"Nog vijf minuten wachten.",e:"five",v:"fem",x:"Five more minutes of waiting.",t:"core",c:0},
{i:144,w:"zes",s:"Ik ben om zes uur thuis.",e:"six",v:"sex",x:"I am home at six o'clock.",t:"core",c:1},
{i:145,w:"zeven",s:"De winkel opent om zeven uur.",e:"seven",v:"sju",x:"The shop opens at seven o'clock.",t:"core",c:0},
{i:146,w:"acht",s:"Het feest begint om acht uur.",e:"eight",v:"åtta",x:"The party starts at eight o'clock.",t:"core",c:1},
{i:147,w:"negen",s:"Ik werk van negen tot vijf.",e:"nine",v:"nio",x:"I work from nine to five.",t:"core",c:1},
{i:148,w:"tien",s:"De les duurt tien minuten.",e:"ten",v:"tio",x:"The lesson lasts ten minutes.",t:"core",c:1},
{i:149,w:"honderd",s:"Dit kost honderd euro.",e:"hundred",v:"hundra",x:"This costs a hundred euros.",t:"core",c:1},
{i:150,w:"duizend",s:"Ik leer duizend woorden!",e:"thousand",v:"tusen",x:"I am learning a thousand words!",t:"core",c:1},
{i:151,w:"de maandag",s:"Op maandag begin ik vroeg.",e:"Monday",v:"måndagen",x:"On Monday I start early.",t:"core",c:1},
{i:152,w:"de vrijdag",s:"Vrijdag gaan we uit eten.",e:"Friday",v:"fredagen",x:"On Friday we are eating out.",t:"core",c:1},
{i:153,w:"de zaterdag",s:"Zaterdag is markt op het plein.",e:"Saturday",v:"lördagen",x:"On Saturday there is a market on the square.",t:"life",c:0},
{i:154,w:"de zondag",s:"Zondag slapen we uit.",e:"Sunday",v:"söndagen",x:"On Sunday we sleep in.",t:"fam",c:1},
{i:155,w:"de ochtend",s:"In de ochtend drink ik thee.",e:"the morning",v:"morgonen",x:"In the morning I drink tea.",t:"core",c:0},
{i:156,w:"de middag",s:"Vanmiddag ga ik sporten.",e:"the afternoon",v:"eftermiddagen",x:"This afternoon I am going to exercise.",t:"core",c:1},
{i:157,w:"de avond",s:"Vanavond kijken we een film.",e:"the evening",v:"kvällen",x:"Tonight we are watching a movie.",t:"fam",c:0},
{i:158,w:"de nacht",s:"De baby sliep de hele nacht.",e:"the night",v:"natten",x:"The baby slept the whole night.",t:"core",c:1},
{i:159,w:"spreken",s:"Ik spreek een beetje Nederlands.",e:"to speak",v:"att tala / prata",x:"I speak a little Dutch.",t:"core",c:0},
{i:160,w:"praten",s:"We praten over het weekend.",e:"to talk",v:"att prata",x:"We are talking about the weekend.",t:"core",c:1},
{i:161,w:"verstaan",s:"Ik versta je niet, kun je langzamer praten?",e:"to understand (hear)",v:"att förstå / uppfatta",x:"I don't understand you, can you speak slower?",t:"core",c:1},
{i:162,w:"begrijpen",s:"Ik begrijp de vraag niet.",e:"to understand",v:"att begripa / förstå",x:"I don't understand the question.",t:"core",c:1},
{i:163,w:"langzaam",s:"Praat alsjeblieft langzaam.",e:"slow",v:"långsam",x:"Please speak slowly.",t:"core",c:1},
{i:164,w:"snel",s:"Nederlanders praten heel snel.",e:"fast",v:"snabb",x:"Dutch people talk very fast.",t:"core",c:0},
{i:165,w:"herhalen",s:"Kunt u dat herhalen, alstublieft?",e:"to repeat",v:"att upprepa",x:"Could you repeat that, please?",t:"core",c:0},
{i:166,w:"betekenen",s:"Wat betekent dit woord?",e:"to mean",v:"att betyda",x:"What does this word mean?",t:"core",c:1},
{i:167,w:"het woord",s:"Ik leer elke dag nieuwe woorden.",e:"the word",v:"ordet",x:"I learn new words every day.",t:"core",c:1},
{i:168,w:"de taal",s:"Nederlands is een leuke taal.",e:"the language",v:"språket",x:"Dutch is a fun language.",t:"core",c:0},
{i:169,w:"leren",s:"Ik leer Nederlands voor mijn vriend.",e:"to learn",v:"att lära sig",x:"I am learning Dutch for my boyfriend.",t:"core",c:1},
{i:170,w:"lezen",s:"Ik lees een boek in het Nederlands.",e:"to read",v:"att läsa",x:"I am reading a book in Dutch.",t:"core",c:1},
{i:171,w:"schrijven",s:"Kun je dat voor me opschrijven?",e:"to write",v:"att skriva",x:"Can you write that down for me?",t:"core",c:1},
{i:172,w:"het boek",s:"Dit boek is echt goed.",e:"the book",v:"boken",x:"This book is really good.",t:"core",c:1},
{i:173,w:"luisteren",s:"Ik luister naar Nederlandse muziek.",e:"to listen",v:"att lyssna",x:"I listen to Dutch music.",t:"core",c:0},
{i:174,w:"kijken",s:"We kijken naar een Nederlandse serie.",e:"to watch / look",v:"att titta",x:"We are watching a Dutch series.",t:"fam",c:0},
{i:175,w:"vragen",s:"Mag ik iets vragen?",e:"to ask",v:"att fråga",x:"May I ask something?",t:"core",c:1},
{i:176,w:"antwoorden",s:"Hij antwoordt altijd in het Engels.",e:"to answer",v:"att svara",x:"He always answers in English.",t:"core",c:0},
{i:177,w:"zeggen",s:"Hoe zeg je dat in het Nederlands?",e:"to say",v:"att säga",x:"How do you say that in Dutch?",t:"core",c:1},
{i:178,w:"heten",s:"Ik heet Anna, en jij?",e:"to be called",v:"att heta",x:"My name is Anna, and you?",t:"core",c:1},
{i:179,w:"het restaurant",s:"Dit restaurant is heel populair.",e:"the restaurant",v:"restaurangen",x:"This restaurant is very popular.",t:"life",c:1},
{i:180,w:"het café",s:"We zitten op het terras van het café.",e:"the café / pub",v:"kaféet",x:"We are sitting on the café terrace.",t:"life",c:1},
{i:181,w:"het terras",s:"Bij mooi weer zit iedereen op het terras.",e:"the terrace / patio",v:"uteserveringen",x:"In nice weather everyone sits on the terrace.",t:"life",c:1},
{i:182,w:"bestellen",s:"Zullen we bestellen?",e:"to order",v:"att beställa",x:"Shall we order?",t:"life",c:1},
{i:183,w:"de rekening",s:"Mogen we de rekening?",e:"the bill",v:"notan / räkningen",x:"May we have the bill?",t:"life",c:1},
{i:184,w:"reserveren",s:"Ik wil een tafel reserveren voor twee.",e:"to reserve",v:"att reservera / boka",x:"I want to reserve a table for two.",t:"life",c:1},
{i:185,w:"de tafel",s:"De tafel bij het raam is vrij.",e:"the table",v:"bordet",x:"The table by the window is free.",t:"life",c:0},
{i:186,w:"de stoel",s:"Is deze stoel vrij?",e:"the chair",v:"stolen",x:"Is this chair free?",t:"life",c:1},
{i:187,w:"proost",s:"Proost, op ons!",e:"cheers",v:"skål",x:"Cheers, to us!",t:"fam",c:0},
{i:188,w:"eet smakelijk",s:"Eet smakelijk allemaal!",e:"enjoy your meal",v:"smaklig måltid",x:"Enjoy your meal everyone!",t:"fam",c:0},
{i:189,w:"het broodje",s:"Ik neem een broodje kaas.",e:"the sandwich / roll",v:"mackan / smörgåsen",x:"I'll take a cheese sandwich.",t:"life",c:0},
{i:190,w:"de patat",s:"Patat met mayonaise, typisch Nederlands.",e:"the fries",v:"pommes fritesen",x:"Fries with mayonnaise, typically Dutch.",t:"life",c:0},
{i:191,w:"de appel",s:"Ik eet elke dag een appel.",e:"the apple",v:"äpplet",x:"I eat an apple every day.",t:"core",c:1},
{i:192,w:"het ei",s:"Wil je een gekookt ei?",e:"the egg",v:"ägget",x:"Do you want a boiled egg?",t:"fam",c:1},
{i:193,w:"de soep",s:"De soep is nog heet.",e:"the soup",v:"soppan",x:"The soup is still hot.",t:"fam",c:1},
{i:194,w:"koken",s:"Wie kookt er vanavond?",e:"to cook",v:"att laga mat / koka",x:"Who is cooking tonight?",t:"fam",c:1},
{i:195,w:"de keuken",s:"De keuken is klein maar fijn.",e:"the kitchen",v:"köket",x:"The kitchen is small but nice.",t:"life",c:1},
{i:196,w:"de kamer",s:"Mijn kamer heeft veel licht.",e:"the room",v:"rummet / kammaren",x:"My room has a lot of light.",t:"life",c:1},
{i:197,w:"de deur",s:"Doe de deur dicht, het tocht.",e:"the door",v:"dörren",x:"Close the door, there is a draft.",t:"life",c:1},
{i:198,w:"het raam",s:"Mag het raam open?",e:"the window",v:"fönstret",x:"Can the window be opened?",t:"life",c:0},
{i:199,w:"de sleutel",s:"Ik ben mijn sleutels kwijt.",e:"the key",v:"nyckeln",x:"I have lost my keys.",t:"life",c:0},
{i:200,w:"de bank",s:"We zitten op de bank een film te kijken.",e:"the couch / bank",v:"soffan / banken",x:"We are sitting on the couch watching a movie.",t:"fam",c:1},
{i:201,w:"het bed",s:"Ik ga naar bed, ik ben moe.",e:"the bed",v:"sängen",x:"I am going to bed, I am tired.",t:"fam",c:0},
{i:202,w:"de douche",s:"Ik neem eerst een douche.",e:"the shower",v:"duschen",x:"I'll take a shower first.",t:"life",c:1},
{i:203,w:"schoonmaken",s:"Zaterdag maken we het huis schoon.",e:"to clean",v:"att städa",x:"On Saturday we clean the house.",t:"fam",c:0},
{i:204,w:"de was",s:"De was hangt buiten.",e:"the laundry",v:"tvätten",x:"The laundry is hanging outside.",t:"life",c:0},
{i:205,w:"helpen",s:"Kun je me even helpen?",e:"to help",v:"att hjälpa",x:"Can you help me for a moment?",t:"core",c:1},
{i:206,w:"even",s:"Wacht even, ik kom eraan.",e:"just / a moment",v:"ett ögonblick / lite",x:"Wait a moment, I am coming.",t:"core",c:0},
{i:207,w:"misschien",s:"Misschien gaan we zondag naar het strand.",e:"maybe",v:"kanske",x:"Maybe we'll go to the beach on Sunday.",t:"core",c:0},
{i:208,w:"natuurlijk",s:"Natuurlijk help ik je!",e:"of course",v:"naturligtvis / såklart",x:"Of course I'll help you!",t:"core",c:1},
{i:209,w:"echt",s:"Dat is echt grappig.",e:"really",v:"verkligen / äkta",x:"That is really funny.",t:"core",c:1},
{i:210,w:"heel",s:"Het is heel gezellig hier.",e:"very",v:"väldigt / hel",x:"It is very cozy here.",t:"core",c:1},
{i:211,w:"te",s:"De koffie is te heet.",e:"too",v:"för",x:"The coffee is too hot.",t:"core",c:0},
{i:212,w:"ook",s:"Ik wil ook een ijsje.",e:"also",v:"också",x:"I also want an ice cream.",t:"core",c:1},
{i:213,w:"nog",s:"Wil je nog een kopje thee?",e:"still / another",v:"ännu / till",x:"Do you want another cup of tea?",t:"core",c:0},
{i:214,w:"al",s:"Ben je al klaar?",e:"already",v:"redan",x:"Are you done already?",t:"core",c:0},
{i:215,w:"maar",s:"Ik wil komen, maar ik moet werken.",e:"but",v:"men",x:"I want to come, but I have to work.",t:"core",c:0},
{i:216,w:"omdat",s:"Ik leer Nederlands omdat ik hier woon.",e:"because",v:"eftersom / därför att",x:"I am learning Dutch because I live here.",t:"core",c:0},
{i:217,w:"en",s:"Brood en kaas, graag.",e:"and",v:"och",x:"Bread and cheese, please.",t:"core",c:0},
{i:218,w:"of",s:"Wil je thee of koffie?",e:"or",v:"eller",x:"Do you want tea or coffee?",t:"core",c:0},
{i:219,w:"met",s:"Ik ga met de fiets.",e:"with",v:"med",x:"I am going by bike.",t:"core",c:1},
{i:220,w:"zonder",s:"Koffie zonder melk, graag.",e:"without",v:"utan",x:"Coffee without milk, please.",t:"core",c:0},
{i:221,w:"voor",s:"Dit cadeau is voor jou.",e:"for",v:"för / åt",x:"This present is for you.",t:"core",c:1},
{i:222,w:"na",s:"Na het eten gaan we wandelen.",e:"after",v:"efter",x:"After dinner we go for a walk.",t:"core",c:0},
{i:223,w:"het cadeau",s:"Ik zoek een cadeau voor zijn moeder.",e:"the present",v:"presenten",x:"I am looking for a present for his mother.",t:"fam",c:0},
{i:224,w:"de verjaardag",s:"Zaterdag is de verjaardag van zijn zus.",e:"the birthday",v:"födelsedagen",x:"Saturday is his sister's birthday.",t:"fam",c:0},
{i:225,w:"gefeliciteerd",s:"Gefeliciteerd met je verjaardag!",e:"congratulations",v:"grattis",x:"Happy birthday!",t:"fam",c:0},
{i:226,w:"het feest",s:"Het feest was erg gezellig.",e:"the party",v:"festen",x:"The party was very fun.",t:"fam",c:1},
{i:227,w:"de taart",s:"Wil je een stukje taart?",e:"the cake / pie",v:"tårtan",x:"Do you want a piece of cake?",t:"fam",c:1},
{i:228,w:"vieren",s:"We vieren het thuis met de familie.",e:"to celebrate",v:"att fira",x:"We celebrate it at home with the family.",t:"fam",c:1},
{i:229,w:"uitnodigen",s:"Ze hebben ons uitgenodigd voor het eten.",e:"to invite",v:"att bjuda in",x:"They invited us for dinner.",t:"fam",c:0},
{i:230,w:"op bezoek",s:"We gaan op bezoek bij oma.",e:"visiting",v:"på besök",x:"We are visiting grandma.",t:"fam",c:1},
{i:231,w:"het strand",s:"In de zomer gaan we naar het strand.",e:"the beach",v:"stranden",x:"In the summer we go to the beach.",t:"life",c:1},
{i:232,w:"het park",s:"Het Vondelpark is mijn favoriete park.",e:"the park",v:"parken",x:"The Vondelpark is my favorite park.",t:"life",c:1},
{i:233,w:"wandelen",s:"Zullen we een rondje wandelen?",e:"to go for a walk",v:"att promenera / vandra",x:"Shall we go for a little walk?",t:"fam",c:1},
{i:234,w:"zwemmen",s:"Kun je in de gracht zwemmen?",e:"to swim",v:"att simma",x:"Can you swim in the canal?",t:"life",c:0},
{i:235,w:"sporten",s:"Ik sport twee keer per week.",e:"to exercise",v:"att träna / sporta",x:"I exercise twice a week.",t:"core",c:1},
{i:236,w:"spelen",s:"De kinderen spelen in het park.",e:"to play",v:"att spela / leka",x:"The children are playing in the park.",t:"core",c:1},
{i:237,w:"de muziek",s:"Ik luister graag naar muziek.",e:"the music",v:"musiken",x:"I like listening to music.",t:"core",c:1},
{i:238,w:"de film",s:"De film begint om negen uur.",e:"the movie",v:"filmen",x:"The movie starts at nine o'clock.",t:"core",c:1},
{i:239,w:"leuk",s:"Wat leuk om je te zien!",e:"nice / fun",v:"kul / trevlig",x:"How nice to see you!",t:"core",c:0},
{i:240,w:"grappig",s:"Jouw vriend is heel grappig.",e:"funny",v:"rolig",x:"Your boyfriend is very funny.",t:"fam",c:0},
{i:241,w:"moeilijk",s:"Nederlands is niet zo moeilijk.",e:"difficult",v:"svår",x:"Dutch is not that difficult.",t:"core",c:0},
{i:242,w:"makkelijk",s:"Deze oefening is makkelijk.",e:"easy",v:"lätt / enkel",x:"This exercise is easy.",t:"core",c:0},
{i:243,w:"belangrijk",s:"Familie is belangrijk voor hem.",e:"important",v:"viktig",x:"Family is important to him.",t:"fam",c:0},
{i:244,w:"druk",s:"Het is druk in de stad vandaag.",e:"busy / crowded",v:"livlig / upptagen",x:"It is busy in the city today.",t:"life",c:0},
{i:245,w:"rustig",s:"Het is lekker rustig in het park.",e:"quiet / calm",v:"lugn",x:"It is nice and quiet in the park.",t:"life",c:0},
{i:246,w:"de mens",s:"Er zijn veel mensen op de markt.",e:"the person / human",v:"människan",x:"There are many people at the market.",t:"core",c:1},
{i:247,w:"de man",s:"Die man woont bij ons in de straat.",e:"the man",v:"mannen",x:"That man lives on our street.",t:"core",c:1},
{i:248,w:"de vrouw",s:"De vrouw in de winkel was aardig.",e:"the woman",v:"kvinnan",x:"The woman in the shop was kind.",t:"core",c:0},
{i:249,w:"het kind",s:"Het kind speelt met de hond.",e:"the child",v:"barnet",x:"The child is playing with the dog.",t:"core",c:0},
{i:250,w:"de hond",s:"Onze buren hebben een lieve hond.",e:"the dog",v:"hunden",x:"Our neighbors have a sweet dog.",t:"core",c:1},
{i:251,w:"de kat",s:"De kat slaapt op de bank.",e:"the cat",v:"katten",x:"The cat is sleeping on the couch.",t:"core",c:1},
{i:252,w:"de buren",s:"De buren komen zaterdag langs.",e:"the neighbors",v:"grannarna",x:"The neighbors are coming by on Saturday.",t:"life",c:0},
{i:253,w:"aardig",s:"De mensen hier zijn aardig.",e:"kind / nice",v:"snäll / trevlig",x:"The people here are kind.",t:"core",c:0},
{i:254,w:"vinden",s:"Ik vind Amsterdam geweldig.",e:"to find / think",v:"att tycka / hitta",x:"I think Amsterdam is great.",t:"core",c:1},
{i:255,w:"denken",s:"Ik denk dat het gaat regenen.",e:"to think",v:"att tänka / tro",x:"I think it is going to rain.",t:"core",c:1},
{i:256,w:"geloven",s:"Ik geloof dat de winkel dicht is.",e:"to believe",v:"att tro",x:"I believe the shop is closed.",t:"core",c:0},
{i:257,w:"hopen",s:"Ik hoop dat je snel beter wordt.",e:"to hope",v:"att hoppas",x:"I hope you get better soon.",t:"core",c:1},
{i:258,w:"proberen",s:"Ik probeer elke dag Nederlands te praten.",e:"to try",v:"att försöka / prova",x:"I try to speak Dutch every day.",t:"core",c:0},
{i:259,w:"beginnen",s:"De cursus begint volgende week.",e:"to begin",v:"att börja",x:"The course begins next week.",t:"core",c:1},
{i:260,w:"stoppen",s:"De tram stopt bij het museum.",e:"to stop",v:"att stanna / stoppa",x:"The tram stops at the museum.",t:"life",c:1},
{i:261,w:"wachten",s:"Ik wacht op je bij de ingang.",e:"to wait",v:"att vänta",x:"I am waiting for you at the entrance.",t:"core",c:1},
{i:262,w:"vergeten",s:"Ik ben mijn ov-kaart vergeten.",e:"to forget",v:"att glömma",x:"I forgot my transit card.",t:"life",c:0},
{i:263,w:"onthouden",s:"Ik kan dat woord niet onthouden.",e:"to remember",v:"att komma ihåg",x:"I can't remember that word.",t:"core",c:0},
{i:264,w:"geven",s:"Kun je me het zout geven?",e:"to give",v:"att ge",x:"Can you give me the salt?",t:"fam",c:1},
{i:265,w:"nemen",s:"Ik neem de trein van acht uur.",e:"to take",v:"att ta",x:"I am taking the eight o'clock train.",t:"life",c:0},
{i:266,w:"pakken",s:"Pak jij de tassen even?",e:"to grab / take",v:"att ta / plocka",x:"Can you grab the bags?",t:"fam",c:1},
{i:267,w:"vinden (kwijt)",s:"Ik kan mijn telefoon niet vinden.",e:"to find",v:"att hitta",x:"I can't find my phone.",t:"core",c:0},
{i:268,w:"de telefoon",s:"Mijn telefoon is bijna leeg.",e:"the phone",v:"telefonen",x:"My phone is almost dead.",t:"core",c:1},
{i:269,w:"bellen",s:"Ik bel je morgen even.",e:"to call",v:"att ringa",x:"I'll call you tomorrow.",t:"core",c:0},
{i:270,w:"de foto",s:"Zullen we een foto maken?",e:"the photo",v:"fotot",x:"Shall we take a photo?",t:"core",c:1},
{i:271,w:"sturen",s:"Stuur me even een berichtje.",e:"to send",v:"att skicka",x:"Send me a message.",t:"core",c:0},
{i:272,w:"het bericht",s:"Ik heb je bericht gelezen.",e:"the message",v:"meddelandet",x:"I read your message.",t:"core",c:0},
{i:273,w:"de afspraak",s:"Ik heb morgen een afspraak bij de tandarts.",e:"the appointment",v:"mötet / tiden",x:"I have a dentist appointment tomorrow.",t:"life",c:0},
{i:274,w:"de dokter",s:"Ik moet naar de dokter.",e:"the doctor",v:"doktorn / läkaren",x:"I have to go to the doctor.",t:"life",c:1},
{i:275,w:"de apotheek",s:"De apotheek is naast de supermarkt.",e:"the pharmacy",v:"apoteket",x:"The pharmacy is next to the supermarket.",t:"life",c:1},
{i:276,w:"de pijn",s:"Ik heb pijn in mijn rug.",e:"the pain",v:"smärtan / ont",x:"I have pain in my back.",t:"core",c:1},
{i:277,w:"het hoofd",s:"Ik heb hoofdpijn.",e:"the head",v:"huvudet",x:"I have a headache.",t:"core",c:1},
{i:278,w:"de hand",s:"Geef me je hand.",e:"the hand",v:"handen",x:"Give me your hand.",t:"core",c:1},
{i:279,w:"het oog",s:"Ze heeft mooie blauwe ogen.",e:"the eye",v:"ögat",x:"She has beautiful blue eyes.",t:"core",c:1},
{i:280,w:"de supermarkt",s:"Ik ga snel even naar de supermarkt.",e:"the supermarket",v:"mataffären",x:"I am quickly going to the supermarket.",t:"life",c:0},
{i:281,w:"de tas",s:"Wil je een tasje erbij?",e:"the bag",v:"väskan / påsen",x:"Do you want a bag with that?",t:"life",c:0},
{i:282,w:"de kassa",s:"Bij welke kassa moet ik zijn?",e:"the checkout",v:"kassan",x:"Which checkout should I go to?",t:"life",c:1},
{i:283,w:"pinnen",s:"Kan ik hier pinnen?",e:"to pay by card",v:"att betala med kort",x:"Can I pay by card here?",t:"life",c:0},
{i:284,w:"open",s:"Is de bakker zondag open?",e:"open",v:"öppen",x:"Is the bakery open on Sunday?",t:"life",c:1},
{i:285,w:"dicht",s:"De winkel is al dicht.",e:"closed",v:"stängd",x:"The shop is already closed.",t:"life",c:0},
{i:286,w:"morgenvroeg",s:"Morgenvroeg ga ik hardlopen.",e:"tomorrow morning",v:"imorgon bitti",x:"Tomorrow morning I am going running.",t:"core",c:0},
{i:287,w:"vanavond",s:"Vanavond koken zijn ouders voor ons.",e:"tonight",v:"ikväll",x:"Tonight his parents are cooking for us.",t:"fam",c:0},
{i:288,w:"vannacht",s:"Vannacht heb ik slecht geslapen.",e:"last night / tonight",v:"i natt",x:"Last night I slept badly.",t:"core",c:0},
{i:289,w:"eergisteren",s:"Eergisteren waren we bij zijn opa.",e:"the day before yesterday",v:"i förrgår",x:"The day before yesterday we were at his grandpa's.",t:"fam",c:0},
{i:290,w:"overmorgen",s:"Overmorgen komt mijn zus aan.",e:"the day after tomorrow",v:"i övermorgon",x:"The day after tomorrow my sister arrives.",t:"fam",c:0},
{i:291,w:"de vakantie",s:"We gaan in augustus op vakantie.",e:"the vacation",v:"semestern",x:"We are going on vacation in August.",t:"core",c:0},
{i:292,w:"het vliegtuig",s:"Het vliegtuig naar Stockholm vertrekt om tien uur.",e:"the airplane",v:"flygplanet",x:"The plane to Stockholm leaves at ten o'clock.",t:"life",c:1},
{i:293,w:"Zweden",s:"In december ga ik naar Zweden.",e:"Sweden",v:"Sverige",x:"In December I am going to Sweden.",t:"fam",c:0},
{i:294,w:"Zweeds",s:"Zweeds en Nederlands lijken op elkaar.",e:"Swedish",v:"svenska",x:"Swedish and Dutch resemble each other.",t:"core",c:0},
{i:295,w:"Nederland",s:"Ik woon nu een jaar in Nederland.",e:"the Netherlands",v:"Nederländerna",x:"I have now lived in the Netherlands for a year.",t:"core",c:1},
{i:296,w:"Nederlands",s:"Mijn Nederlands wordt steeds beter.",e:"Dutch",v:"nederländska",x:"My Dutch keeps getting better.",t:"core",c:1},
{i:297,w:"trots",s:"Ik ben trots op jou.",e:"proud",v:"stolt",x:"I am proud of you.",t:"fam",c:1},
{i:298,w:"beter",s:"Oefening maakt je beter.",e:"better",v:"bättre",x:"Practice makes you better.",t:"core",c:1},
{i:299,w:"steeds",s:"Het gaat steeds beter met mijn Nederlands.",e:"increasingly / all the time",v:"allt / hela tiden",x:"My Dutch is getting better all the time.",t:"core",c:0},
{i:300,w:"succes",s:"Succes met je Nederlands!",e:"good luck",v:"lycka till",x:"Good luck with your Dutch!",t:"core",c:1},
];
