// Lezen — graded mini-stories. m = words-started milestone to unlock.
// gloss = words used that fall outside the learned range (the "i+1" items).
const STORIES=[
{m:50,t:"Koffie in de ochtend",txt:"Goedemorgen! Ik ben in het huis aan de gracht. Het is vroeg. Ik drink koffie met melk en ik eet brood met kaas. Mijn vriend slaapt nog. De stad is rustig en mooi. Vandaag ga ik naar het werk met de fiets. Het weer is goed. Wat een mooie dag!",gloss:{"nog":"still","rustig":"quiet"}},
{m:100,t:"Naar de markt",txt:"Vandaag is het zaterdag. Wij gaan naar de markt. Op de markt kopen we brood, kaas, en bloemen. De kaas is lekker maar duur. Ik betaal met pin. Daarna drinken we koffie in een café bij de gracht. Mijn vriend eet een broodje. We praten en lachen. Het is druk in de stad, maar heel gezellig.",gloss:{"daarna":"after that","bloemen":"flowers","lachen":"to laugh"}},
{m:150,t:"Een avond met de familie",txt:"Vanavond eten we bij zijn ouders. Zijn moeder kookt soep en zijn vader maakt het avondeten. Oma is er ook! Ze vertelt over vroeger. Ik versta niet alles, maar ik luister goed. Na het eten drinken we thee en eten we taart. Om elf uur gaan we naar huis. In de tram zegt mijn vriend: je Nederlands wordt steeds beter! Ik ben blij.",gloss:{"vertelt":"tells","vroeger":"the old days","wordt":"becomes"}},
{m:200,t:"De sleutels",txt:"Het is maandag en ik ben moe. Ik sta vroeg op, neem een douche en maak het ontbijt. Maar waar zijn mijn sleutels? Ik kijk in de keuken, in de kamer, en op de tafel. Niets! Ik bel mijn vriend. Hij lacht en zegt: kijk in je jas! En ja, daar zijn ze. Ik ben te laat voor het werk, maar dat is niet erg. Fouten maken hoort bij de maandag.",gloss:{"erg":"bad / very","hoort bij":"is part of"}},
{m:250,t:"Zondag in het park",txt:"Het is zondag en de zon schijnt. We wandelen samen een rondje door het park. Veel mensen sporten, kinderen spelen, en honden lopen blij in het gras. We zitten op een bankje en eten een ijsje. Mijn vriend maakt een foto van mij. Ik stuur de foto naar mijn zus in Zweden. Ze antwoordt meteen: wat mooi! Kom je snel op bezoek? Misschien in december, schrijf ik. Ik mis haar soms.",gloss:{"schijnt":"shines","het gras":"the grass","bankje":"little bench"}},
{m:300,t:"Bezoek uit Zweden",txt:"Mijn zus komt op bezoek! Haar vliegtuig komt om tien uur aan. Ik wacht op het station met bloemen. Daar is ze! We praten Zweeds en dat is fijn. Ik laat haar de stad zien: de grachten, de markt, en natuurlijk mijn favoriete café. Ze vindt Amsterdam prachtig. 's Avonds koken we samen met mijn vriend. Hij probeert Zweeds te praten en wij moeten zo hard lachen. Wat een gezellige week wordt dit!",gloss:{"haar":"her","fijn":"nice","prachtig":"gorgeous"}},
{m:350,t:"Regen, regen, regen",txt:"Het regent al drie dagen. De wind is sterk en mijn paraplu is kapot. Ik fiets naar het werk en word helemaal nat. Mijn collega lacht: welkom in Nederland! Binnen drink ik warme thee. Na het werk ga ik naar huis. Mijn vriend heeft soep gemaakt en de lampen zijn aan. We blijven binnen en kijken een film op de bank. Buiten regent het, maar binnen is het warm en gezellig. Misschien is de herfst zo slecht nog niet.",gloss:{"helemaal":"completely","gemaakt":"made"}},
{m:400,t:"Koken met zijn moeder",txt:"Vandaag leer ik koken van zijn moeder. We maken soep met groente: aardappelen, uien en tomaten. Ik snijd de uien en moet huilen. Zij lacht en geeft me een glas water. De soep ruikt heerlijk. We eten samen met vers brood en boter. Eet smakelijk, zegt iedereen. De soep is een beetje te zout, maar niemand zegt iets. Na het eten krijg ik het recept mee. Volgende week kook ik het zelf!",gloss:{"het recept":"the recipe","een beetje":"a little"}},
{m:450,t:"De nieuwe jas",txt:"De winter komt en ik heb een warme jas nodig. In de winkel pas ik een blauwe jas. Te klein! De vrouw van de winkel haalt een andere maat. Deze past goed en hij is niet duur. Ik koop ook een sjaal en warme sokken. Bij de kassa betaal ik met pin. Buiten is het koud, maar mijn nieuwe jas is heerlijk warm. Klaar voor de winter!",gloss:{"past":"fits"}},
{m:500,t:"Een brief van de gemeente",txt:"Er ligt een brief van de gemeente op de tafel. Ik moet een formulier invullen voor mijn paspoort. Het formulier is in het Nederlands en best moeilijk. Mijn vriend helpt me. Wat betekent dit woord, vraag ik. Hij legt alles uit. Na een uur zijn we klaar. Komt goed, zegt hij. De volgende dag breng ik het formulier naar het gemeentehuis. De vrouw daar is aardig en spreekt langzaam met mij. Alles is geregeld. Wat ben ik trots op mezelf!",gloss:{"invullen":"to fill in","geregeld":"arranged","mezelf":"myself"}},
{m:550,t:"Ziek thuis",txt:"Ik voel me niet goed. Mijn hoofd doet pijn en ik heb koorts. Ik blijf thuis in bed. Mijn vriend belt de huisarts en haalt medicijnen bij de apotheek. Hij zet thee en maakt soep voor mij. Wat lief! Ik slaap bijna de hele dag. De kat ligt naast mij op het bed. Na drie dagen voel ik me beter. Beterschap werkt het beste met veel slaap, thee, en een lieve vriend.",gloss:{"het beste":"the best"}},
{m:600,t:"Koningsdag",txt:"Vandaag is het Koningsdag en iedereen draagt oranje! De hele stad is één groot feest. Op de grachten zijn boten met muziek. We lopen door het centrum en kopen oude boeken op de markt. Kinderen verkopen taart en spelen muziek op het plein. We drinken een biertje op een terras in de zon. 's Avonds zijn we moe maar heel blij. Dit is mijn eerste Koningsdag, zeg ik. Zeker niet je laatste, lacht mijn vriend. Proost, op Nederland!",gloss:{"boten":"boats","verkopen":"sell","zeker":"certainly"}},
{m:650,t:"De discussie",txt:"Bij het avondeten hebben we een discussie. Volgens mij is de winter in Zweden mooier dan hier. Mijn vriend is het er niet mee eens. Hier kun je soms schaatsen op de grachten, zegt hij. Dat klopt, zeg ik, maar in Zweden hebben we echte sneeuw en meer licht in de zomer. We vergelijken de twee landen de hele avond. Eigenlijk hebben we allebei gelijk: beide landen zijn prachtig. Daarom gaan we in februari naar Zweden én blijven we in december hier.",gloss:{"de discussie":"the discussion","het licht":"the light"}},
{m:700,t:"Verliefd in Amsterdam",txt:"Vandaag vroeg zijn moeder: waar hebben jullie elkaar eigenlijk ontmoet? Ik vertelde het verhaal. Twee jaar geleden was ik op vakantie in Amsterdam. In een klein café om de hoek vroeg ik in het Engels om koffie. Hij stond achter mij en zei iets grappigs. We hebben de hele middag gepraat. Ik was meteen verliefd, maar ook verlegen. Na de vakantie hebben we elk weekend gebeld. Een jaar later ben ik verhuisd. Soms verandert je leven ineens, en dat is prachtig.",gloss:{"geleden":"ago","gebeld":"called"}},
{m:750,t:"De lekke band",txt:"Wat een dag! Vanochtend had mijn fiets een lekke band. Natuurlijk regende het ook. Ik moest lopen naar het werk en kwam te laat bij de vergadering. Mijn collega lachte: dat is pas echt Nederlands, een lekke band in de regen! Na het werk heeft mijn vriend de band gerepareerd. Hij kan dat heel goed. Als dank heb ik bitterballen gehaald voor bij de borrel. Eind goed, al goed: we zaten samen op de bank, warm en droog, met een biertje erbij.",gloss:{"pas echt":"truly","als dank":"as a thank-you","eind goed, al goed":"all's well that ends well"}},
{m:800,t:"Pakjesavond",txt:"Vanavond vieren we pakjesavond bij zijn ouders. Iedereen heeft een cadeautje en een gedicht. Het gedicht moet grappig zijn en een beetje gek. Zijn moeder heeft een gedicht over mijn fietsen geschreven: ik fiets namelijk nog steeds als een toerist! Iedereen moest hard lachen, ik ook. We eten pepernoten en drinken warme chocolademelk. Ik heb een gedicht in het Nederlands geschreven, met een klein beetje hulp. Iedereen was verrast. Dit is misschien wel mijn favoriete Nederlandse traditie.",gloss:{"de chocolademelk":"the hot chocolate","de traditie":"the tradition"}},
{m:850,t:"Een dagje weg",txt:"We hebben allebei een vrije dag genomen en zijn met de trein naar Haarlem gegaan. Geen spits, geen vertraging: alles ging goed. In Haarlem zijn we door het centrum gewandeld en hebben we op een terrasje geluncht. Daarna een rondje door het museum. Op de terugweg kwamen we toevallig zijn oude collega tegen in de trein. Kleine wereld! Thuis hebben we eten besteld, want koken na zo'n dag? Geen zin. Het was een perfecte dag, eerlijk gezegd.",gloss:{"de terugweg":"the way back","kleine wereld":"small world","zo'n":"such a"}},
{m:900,t:"Het misverstand",txt:"Vandaag heb ik me vergist, en hoe! Ik had om tien uur een afspraak bij de kapper. Dacht ik. Maar de afspraak was om half tien, en in het Nederlands betekent half tien dus negen uur dertig! Ik kwam een half uur te laat binnen. Gelukkig was de kapper vriendelijk en had ze nog tijd. Iedereen maakt die fout, zei ze, vooral mensen uit het buitenland. Nou ja, in het Zweeds werkt het precies hetzelfde, dus eigenlijk heb ik geen excuus. Dom van mij! Maar mijn haar zit nu wel goed.",gloss:{"het misverstand":"the misunderstanding","het excuus":"the excuse","nou ja":"oh well"}},
{m:950,t:"Bezoek van mama",txt:"Mijn moeder logeert deze week bij ons. Het logeerbed staat in de woonkamer en het huis is vol. Gisteren heb ik haar de stad laten zien: de gevels aan de gracht, de bloemenmarkt, en natuurlijk ons favoriete plekje aan het water. Ze vond alles prachtig, maar de smalle trappen vond ze gevaarlijk! Vanavond kookt mijn vriend voor ons. Hij is zenuwachtig, want mijn moeder is eerlijk over eten. Maar het wordt vast gezellig. Twee talen aan één tafel, en iedereen begrijpt elkaar toch.",gloss:{"vast":"surely"}},
{m:1000,t:"Duizend woorden",txt:"Vandaag is het zover: ik ken duizend Nederlandse woorden! Toen ik begon, kon ik alleen hallo en dank je wel zeggen. Nu praat ik met de buren, bestel ik zonder problemen op het terras, en versta ik de gesprekken bij het avondeten. Natuurlijk maak ik nog fouten, maar fouten maken hoort bij leren. Mijn vriend is trots op mij, en eerlijk gezegd ben ik ook trots op mezelf. We vieren het vanavond met taart en een goed glas wijn. Op de volgende duizend woorden. Proost! Amsterdam voelt nu echt als thuis.",gloss:{"zover":"the moment (has come)","mezelf":"myself"}},
];
