// Mil — graded mini-stories for English speakers learning Spanish.
// m = milestone (words started) to unlock. Peninsular Spanish, genuine Spanish culture.
const STORIES_ES=[
{m:50,t:"Café por la mañana",txt:"¡Hola! Estoy en un piso pequeño en Madrid. Es temprano. Tomo café con leche y como pan con queso. Fuera hace sol. Hoy voy al centro en bici. El tiempo está muy bien. ¡Qué buen día!",gloss:{"fuera":"outside","el centro":"downtown"}},
{m:100,t:"La siesta",txt:"En España, entre las dos y las cinco, muchas tiendas cierran. Es la hora de comer y, para algunos, la hora de la siesta. Hoy hace mucho calor, así que después de comer me tumbo un rato en el sofá. No duermo mucho, solo veinte minutos, pero me siento mejor. Por la tarde, cuando baja el calor, todo el mundo sale otra vez a la calle. La vida aquí tiene un ritmo diferente, y me gusta.",gloss:{"un rato":"a while","el ritmo":"the rhythm"}},
{m:150,t:"El mercado del sábado",txt:"Hoy es sábado. Voy al mercado con mi amiga Laura. Compramos pan, queso y flores. El queso es rico pero un poco caro. Pago con tarjeta. Después tomamos un café en un bar cerca del mercado. Laura pide una tostada con tomate. Hablamos y nos reímos mucho. Hay mucha gente en la calle, pero se está muy a gusto.",gloss:{"la tostada":"the toast","a gusto":"comfortable, at ease"}},
{m:200,t:"Las llaves",txt:"¡Qué día! Esta mañana no encontraba las llaves. Miré en la cocina, en el salón y sobre la mesa. ¡Nada! Llamé a mi amigo Carlos. Se rió y me dijo: ¡mira en el abrigo! Y sí, allí estaban. Llegué tarde al trabajo, pero no pasa nada. Cometer errores es normal, sobre todo un lunes.",gloss:{"sobre todo":"especially"}},
{m:250,t:"Domingo en el parque",txt:"Es domingo y hace sol. Doy un paseo por el parque. Mucha gente hace deporte, los niños juegan, y los perros corren felices por la hierba. Me siento en un banco y como un helado. Hago una foto del parque y se la envío a mi amiga en Londres. Ella responde enseguida: ¡qué bonito! ¿Vienes pronto de visita? Quizás en diciembre, le escribo. A veces la echo de menos.",gloss:{"la hierba":"the grass","el banco":"the bench"}},
{m:300,t:"Visita desde Londres",txt:"¡Mi amiga viene de visita! Su avión llega a las diez. La espero en el aeropuerto con flores. ¡Ahí está! Hablamos inglés y se siente bien. Le enseño la ciudad: el casco antiguo, el mercado, y por supuesto mi bar favorito. Le encanta Madrid. Por la noche cocinamos juntos con mis compañeros de piso. Ella intenta hablar español y nos reímos muchísimo. ¡Qué semana tan divertida!",gloss:{"el casco antiguo":"the old town"}},
{m:350,t:"Lluvia, lluvia, lluvia",txt:"Lleva tres días lloviendo. Hace mucho viento y mi paraguas está roto. Voy en bici al trabajo y me empapo completamente. Mi compañero se ríe: ¡bienvenido a Inglaterra, no a España! Dentro tomo un té caliente. Después del trabajo vuelvo a casa. Mis compañeros de piso han hecho sopa y las luces están encendidas. Nos quedamos dentro y vemos una película en el sofá. Fuera llueve, pero dentro se está calentito y a gusto. Quizás el otoño no está tan mal.",gloss:{"empapo":"I get soaked","encendidas":"turned on","calentito":"nice and warm"}},
{m:400,t:"Cocinando con un amigo español",txt:"Hoy aprendo a cocinar con mi amigo español, Javier. Hacemos una tortilla española: patata, huevo y cebolla. Corto la cebolla y tengo que llorar. Él se ríe y me da un vaso de agua. La tortilla huele genial. Comemos juntos con pan fresco. Que aproveche, dice él. La tortilla está un poco salada, pero nadie dice nada. Después me da la receta. ¡La próxima semana la hago yo solo!",gloss:{"salada":"salty","solo":"alone / by myself"}},
{m:450,t:"El abrigo nuevo",txt:"Llega el invierno y necesito un abrigo caliente. En la tienda me pruebo un abrigo azul. ¡Demasiado pequeño! La chica de la tienda trae otra talla. Este me queda bien y no es caro. También compro una bufanda y calcetines de lana. En la caja pago con tarjeta. Fuera hace frío, pero mi abrigo nuevo es muy calentito. ¡Listo para el invierno!",gloss:{"de lana":"woolen","listo":"ready"}},
{m:500,t:"Una carta del ayuntamiento",txt:"Hay una carta del ayuntamiento sobre la mesa. Tengo que rellenar un formulario para mi pasaporte. El formulario está en español y es bastante difícil. Mi amiga Sara me ayuda. ¿Qué significa esta palabra?, pregunto. Ella me explica todo. Después de una hora, terminamos. Todo saldrá bien, me dice. Al día siguiente llevo el formulario al ayuntamiento. La mujer allí es amable y habla despacio conmigo. Todo está en orden. ¡Qué orgullosa estoy de mí misma!",gloss:{"en orden":"in order","misma":"myself"}},
{m:550,t:"Enfermo en casa",txt:"No me siento bien. Me duele la cabeza y tengo fiebre. Me quedo en cama. Mi amiga llama a la farmacia y me trae medicina. Prepara té y hace sopa para mí. ¡Qué amable! Duermo casi todo el día. El gato está a mi lado en la cama. Después de tres días, me siento mejor. Que te mejores funciona mejor con mucho descanso, té, y una buena amiga.",gloss:{"a mi lado":"next to me"}},
{m:600,t:"Flamenco en Sevilla",txt:"Este fin de semana estoy en Sevilla con unos amigos. Por la noche vamos a un pequeño local a ver flamenco. La bailaora lleva un vestido rojo precioso. El guitarrista toca muy rápido, y el cantaor canta con mucha fuerza. No entiendo todas las palabras, pero siento la emoción. Después, mis amigos me explican que el flamenco viene de Andalucía y tiene mucha historia. Salimos del local tarde, casi a las dos de la madrugada. ¡Qué noche tan especial!",gloss:{"la bailaora":"the flamenco dancer","el cantaor":"the flamenco singer","la fuerza":"the force / power"}},
{m:650,t:"La discusión",txt:"Durante la cena tenemos una pequeña discusión. En mi opinión, el invierno es más bonito en Inglaterra. Mi amigo español no está de acuerdo. Aquí en invierno hace sol casi todos los días, dice. Eso es verdad, digo yo, pero en Inglaterra tenemos nieve de verdad y más luz en verano. Comparamos los dos países toda la noche. En realidad, los dos tenemos razón: los dos países son preciosos. Por eso, en febrero voy a Inglaterra, y me quedo aquí en diciembre.",gloss:{"la discusión":"the discussion","la luz":"the light"}},
{m:700,t:"Cómo nos conocimos",txt:"Hoy mi compañera de piso me preguntó: ¿cómo os conocisteis tú y Javier? Le conté la historia. Hace dos años estaba de vacaciones en Sevilla. En un bar pequeño pedí un café en inglés. Él estaba detrás de la barra y me dijo algo gracioso. Hablamos toda la tarde. Me enamoré enseguida, pero también estaba nerviosa. Después de las vacaciones nos llamábamos cada fin de semana. Un año después me mudé aquí. A veces la vida cambia de repente, y eso es precioso.",gloss:{"la barra":"the bar counter","enamoré":"fell in love"}},
{m:750,t:"La rueda pinchada",txt:"¡Qué día! Esta mañana tenía la rueda de la bici pinchada. Y encima llovía. Tuve que ir andando al trabajo y llegué tarde a la reunión. Mi compañero se rió: ¡eso sí que es típico! Después del trabajo, mi amigo Javier me arregló la rueda. Se le da genial. Como agradecimiento, compré unas bravas para la ronda. Al final del día estábamos en el sofá, calentitos y secos, con una cerveza. Bien está lo que bien acaba.",gloss:{"encima":"on top of that","el agradecimiento":"the thanks / gratitude","bien está lo que bien acaba":"all's well that ends well"}},
{m:800,t:"El Camino de Santiago",txt:"Este verano hago una parte del Camino de Santiago con dos amigas. Caminamos unos veinte kilómetros al día. Por la mañana hace fresco, pero por la tarde hace mucho calor. En cada pueblo paramos a tomar agua y descansar los pies. La gente en el camino es muy amable; todos se ayudan. Una noche dormimos en un albergue con otros caminantes de Alemania, Francia y Corea. Es difícil, pero también es una experiencia preciosa. Todavía nos quedan varios días hasta Santiago.",gloss:{"el albergue":"the hostel","el caminante":"the pilgrim / walker"}},
{m:850,t:"Un día fuera",txt:"Mi amiga y yo nos tomamos el día libre y vamos en tren a Toledo. Sin hora punta, sin retraso: todo va bien. En Toledo paseamos por el casco antiguo y comemos en una terraza. Después una visita guiada por la catedral. De vuelta, por casualidad, nos encontramos con su antiguo compañero de trabajo en el tren. ¡Qué casualidad! En casa pedimos comida a domicilio, porque, ¿cocinar después de un día así? Ni hablar. Fue un día perfecto, sinceramente.",gloss:{"de vuelta":"on the way back","ni hablar":"no way"}},
{m:900,t:"El malentendido",txt:"Hoy me he equivocado, ¡y de qué manera! Tenía cita en la peluquería a las diez. O eso pensaba. Pero la cita era a las diez menos cuarto, y en español eso significa nueve cuarenta y cinco, ¡no diez y cuarto! Llegué quince minutos tarde. Por suerte, la peluquera fue amable y todavía tenía tiempo. Todo el mundo comete ese error, me dijo, sobre todo la gente extranjera. Bueno, en inglés funciona igual, así que no tengo excusa. ¡Qué tonta! Pero mi pelo ha quedado genial.",gloss:{"el malentendido":"the misunderstanding","la excusa":"the excuse"}},
{m:950,t:"Visita de mi madre",txt:"Mi madre se queda en casa esta semana. La cama supletoria está en el salón y la casa está llena. Ayer le enseñé la ciudad: las fachadas del casco antiguo, el mercado de flores, y por supuesto nuestro sitio favorito junto al río. Le encantó todo, pero las escaleras tan estrechas le parecieron peligrosas. Esta noche cocina mi compañero de piso para nosotras. Está nervioso, porque mi madre es sincera con la comida. Pero seguro que será una noche muy agradable. Dos idiomas en una mesa, y todos se entienden igualmente.",gloss:{"seguro":"surely","igualmente":"all the same"}},
{m:1000,t:"Mil palabras",txt:"¡Hoy es el día! Ya conozco mil palabras en español. Cuando empecé, solo sabía decir hola y gracias. Ahora hablo con los vecinos, pido en el bar sin problema, y entiendo las conversaciones en la cena. Claro que todavía cometo errores, pero cometer errores es parte de aprender. Mis amigos están orgullosos de mí, y sinceramente, yo también estoy orgullosa de mí misma. Lo celebramos esta noche con tarta y una buena copa de vino. Por las próximas mil palabras. ¡Salud! Madrid ya se siente de verdad como en casa.",gloss:{"la copa":"the glass (of wine)"}},
];
