// Mille — graded mini-stories for English speakers learning French.
// m = milestone (words started) to unlock. France French, genuine French culture.
const STORIES_FR=[
{m:50,t:"Café le matin",txt:"Bonjour ! Je suis dans un petit appartement à Paris. Il est tôt. Je bois un café avec du lait et je mange du pain avec du fromage. Dehors, il fait soleil. Aujourd'hui, je vais au centre-ville à vélo. Le temps est très beau. Quelle belle journée !",gloss:{"dehors":"outside","le centre-ville":"downtown"}},
{m:100,t:"La terrasse",txt:"En France, quand il fait beau, tout le monde est en terrasse. Aujourd'hui, il fait très chaud, alors après le déjeuner, je vais m'asseoir en terrasse avec un café. Je regarde les gens passer dans la rue. C'est une des choses que j'aime le plus ici : ce rythme tranquille, cette habitude de s'asseoir dehors juste pour regarder la vie. La vie ici a un rythme différent, et j'aime bien ça.",gloss:{"le rythme":"the rhythm"}},
{m:150,t:"Le marché du samedi",txt:"Aujourd'hui, c'est samedi. Je vais au marché avec mon amie Laura. On achète du pain, du fromage et des fleurs. Le fromage est bon mais un peu cher. Je paye par carte. Ensuite, on prend un café dans un bar près du marché. Laura commande une tartine avec de la confiture. On discute et on rit beaucoup. Il y a beaucoup de monde dans la rue, mais on est très bien.",gloss:{"la tartine":"the open-faced sandwich","la confiture":"the jam"}},
{m:200,t:"Les clés",txt:"Quelle journée ! Ce matin, je ne trouvais pas mes clés. J'ai regardé dans la cuisine, dans le salon et sur la table. Rien ! J'ai appelé mon ami Karim. Il a ri et m'a dit : regarde dans ton manteau ! Et oui, elles étaient là. Je suis arrivé en retard au travail, mais ce n'est pas grave. Faire des erreurs, c'est normal, surtout un lundi.",gloss:{"surtout":"especially"}},
{m:250,t:"Dimanche au parc",txt:"C'est dimanche et il fait beau. Je me promène dans le parc. Beaucoup de gens font du sport, les enfants jouent, et les chiens courent joyeusement sur l'herbe. Je m'assois sur un banc et je mange une glace. Je prends une photo du parc et je l'envoie à mon amie à Londres. Elle répond tout de suite : c'est magnifique ! Tu viens bientôt me rendre visite ? Peut-être en décembre, je lui écris. Parfois, elle me manque.",gloss:{"l'herbe":"the grass","le banc":"the bench"}},
{m:300,t:"Visite de Londres",txt:"Mon amie vient me rendre visite ! Son avion arrive à dix heures. Je l'attends à l'aéroport avec des fleurs. La voilà ! On parle anglais et ça lui fait du bien. Je lui montre la ville : le vieux centre, le marché, et bien sûr mon bar préféré. Elle adore Paris. Le soir, on cuisine ensemble avec mes colocataires. Elle essaie de parler français et on rit beaucoup. Quelle semaine amusante !",gloss:{"le colocataire":"the roommate"}},
{m:350,t:"Pluie, pluie, pluie",txt:"Ça fait trois jours qu'il pleut. Il y a beaucoup de vent et mon parapluie est cassé. Je vais au travail à vélo et je suis complètement trempé. Mon collègue rit : bienvenue en Angleterre, pas en France ! À l'intérieur, je bois un thé chaud. Après le travail, je rentre à la maison. Mes colocataires ont fait de la soupe et les lumières sont allumées. On reste à l'intérieur et on regarde un film sur le canapé. Dehors, il pleut, mais à l'intérieur, on est bien au chaud. Peut-être que l'automne n'est pas si mal.",gloss:{"trempé":"soaked","allumées":"turned on"}},
{m:400,t:"Cuisiner avec un ami français",txt:"Aujourd'hui, j'apprends à cuisiner avec mon ami français, Julien. On fait des crêpes : farine, œufs et lait. Je mélange la pâte et j'en mets partout. Il rit et me donne un torchon. Les crêpes sentent très bon. On les mange ensemble avec du sucre et du citron. Bon appétit, dit-il. La première crêpe est un peu ratée, mais personne ne dit rien. Ensuite, il me donne la recette. La semaine prochaine, je les fais tout seul !",gloss:{"le torchon":"the kitchen towel","ratée":"messed up / a failure"}},
{m:450,t:"Le nouveau manteau",txt:"L'hiver arrive et j'ai besoin d'un manteau chaud. Dans le magasin, j'essaie un manteau bleu. Trop petit ! La vendeuse apporte une autre taille. Celui-ci me va bien et n'est pas cher. J'achète aussi une écharpe et des chaussettes en laine. À la caisse, je paye par carte. Dehors, il fait froid, mais mon nouveau manteau est bien chaud. Prêt pour l'hiver !",gloss:{"en laine":"woolen","prêt":"ready"}},
{m:500,t:"Une lettre de la mairie",txt:"Il y a une lettre de la mairie sur la table. Je dois remplir un formulaire pour mon passeport. Le formulaire est en français et il est plutôt difficile. Mon amie Sara m'aide. Qu'est-ce que ce mot veut dire ?, je demande. Elle m'explique tout. Après une heure, on a fini. Tout ira bien, me dit-elle. Le lendemain, j'apporte le formulaire à la mairie. La femme là-bas est gentille et me parle lentement. Tout est en ordre. Comme je suis fière de moi-même !",gloss:{"en ordre":"in order"}},
{m:550,t:"Malade à la maison",txt:"Je ne me sens pas bien. J'ai mal à la tête et de la fièvre. Je reste au lit. Mon amie appelle la pharmacie et m'apporte des médicaments. Elle prépare du thé et fait de la soupe pour moi. Comme c'est gentil ! Je dors presque toute la journée. Le chat est à côté de moi sur le lit. Après trois jours, je me sens mieux. Bon rétablissement fonctionne mieux avec beaucoup de repos, du thé, et une bonne amie.",gloss:{"à côté de moi":"next to me"}},
{m:600,t:"Un concert au parc",txt:"Ce week-end, il y a un petit concert gratuit dans le parc. On y va avec des amis en fin d'après-midi. Le groupe joue de la chanson française et tout le monde chante. Je ne connais pas toutes les paroles, mais je sens l'ambiance. Après, mes amis m'expliquent que ce genre de concert est très courant l'été à Paris, souvent gratuit et organisé par la mairie. On rentre tard, presque à minuit, en discutant de la musique. Quelle belle soirée !",gloss:{"les paroles":"the lyrics","l'ambiance":"the atmosphere"}},
{m:650,t:"La petite dispute",txt:"Pendant le dîner, on a une petite dispute. À mon avis, l'hiver est plus joli en Angleterre. Mon ami français n'est pas d'accord. Ici, en hiver, il fait soleil presque tous les jours, dit-il. C'est vrai, dis-je, mais en Angleterre, on a de la vraie neige et plus de lumière en été. On compare les deux pays toute la soirée. En fait, on a raison tous les deux : les deux pays sont magnifiques. C'est pour ça qu'en février, je vais en Angleterre, et je reste ici en décembre.",gloss:{"la dispute":"the argument","la lumière":"the light"}},
{m:700,t:"Comment on s'est rencontrés",txt:"Aujourd'hui, ma colocataire m'a demandé : comment vous êtes-vous rencontrés, toi et Julien ? Je lui ai raconté l'histoire. Il y a deux ans, j'étais en vacances à Nice. Dans un petit bar, j'ai commandé un café en anglais. Il était derrière le comptoir et m'a dit quelque chose de drôle. On a discuté toute l'après-midi. Je suis tombée amoureuse tout de suite, mais j'étais aussi nerveuse. Après les vacances, on s'appelait chaque week-end. Un an après, j'ai déménagé ici. Parfois, la vie change soudainement, et c'est magnifique.",gloss:{"le comptoir":"the bar counter","tombée amoureuse":"fell in love"}},
{m:750,t:"Le pneu crevé",txt:"Quelle journée ! Ce matin, j'avais un pneu de vélo crevé. Et en plus, il pleuvait. J'ai dû aller à pied au travail et je suis arrivé en retard à la réunion. Mon collègue a ri : ça, c'est typique ! Après le travail, mon ami Julien a réparé la roue. Il est très doué pour ça. Comme remerciement, j'ai acheté du fromage pour la tournée. À la fin de la journée, on était sur le canapé, bien au chaud et au sec, avec un verre de vin. Tout est bien qui finit bien.",gloss:{"le remerciement":"the thanks / gratitude","doué":"skilled"}},
{m:800,t:"Le Chemin de Compostelle",txt:"Cet été, je fais une partie du Chemin de Compostelle avec deux amies. On marche environ vingt kilomètres par jour. Le matin, il fait frais, mais l'après-midi, il fait très chaud. Dans chaque village, on s'arrête pour boire de l'eau et reposer nos pieds. Les gens sur le chemin sont très gentils ; tout le monde s'entraide. Une nuit, on dort dans un gîte avec d'autres marcheurs venus d'Allemagne, de Corée et du Canada. C'est difficile, mais c'est aussi une expérience magnifique. Il nous reste encore plusieurs jours avant d'arriver.",gloss:{"le gîte":"the hostel","le marcheur":"the pilgrim / walker"}},
{m:850,t:"Une journée dehors",txt:"Mon amie et moi, on prend notre jour de congé et on va en train à Chartres. Pas d'heure de pointe, pas de retard : tout se passe bien. À Chartres, on se promène dans le vieux centre et on mange en terrasse. Ensuite, une visite guidée de la cathédrale. Sur le chemin du retour, par hasard, on croise son ancien collègue dans le train. Quel hasard ! À la maison, on commande à emporter, parce que cuisiner après une journée pareille ? Pas question. C'était une journée parfaite, honnêtement.",gloss:{"pas question":"no way"}},
{m:900,t:"Le malentendu",txt:"Aujourd'hui, je me suis trompée, et pas qu'un peu ! J'avais rendez-vous chez le coiffeur à dix heures moins le quart. Enfin, c'est ce que je pensais. Mais en français, dix heures moins le quart, ça veut dire neuf heures quarante-cinq, pas dix heures et quart ! Je suis arrivée quinze minutes en retard. Heureusement, la coiffeuse a été gentille et avait encore le temps. Tout le monde fait cette erreur, m'a-t-elle dit, surtout les étrangers. Bon, en anglais, c'est pareil, donc je n'ai pas d'excuse. Que je suis bête ! Mais mes cheveux sont superbes.",gloss:{"le malentendu":"the misunderstanding","l'excuse":"the excuse"}},
{m:950,t:"Visite de ma mère",txt:"Ma mère reste à la maison cette semaine. Le lit d'appoint est dans le salon et la maison est pleine. Hier, je lui ai montré la ville : les façades du vieux centre, le marché aux fleurs, et bien sûr notre endroit préféré au bord de l'eau. Elle a adoré, mais les escaliers si étroits lui ont semblé dangereux. Ce soir, mon colocataire cuisine pour nous. Il est nerveux, parce que ma mère est honnête sur la nourriture. Mais je suis sûre que ce sera une belle soirée. Deux langues à une table, et tout le monde se comprend quand même.",gloss:{"quand même":"all the same"}},
{m:1000,t:"Mille mots",txt:"Aujourd'hui, c'est le grand jour ! Je connais maintenant mille mots en français. Quand j'ai commencé, je savais seulement dire bonjour et merci. Maintenant, je discute avec les voisins, je commande au bar sans problème, et je comprends les conversations pendant le dîner. Bien sûr, je fais encore des erreurs, mais faire des erreurs, ça fait partie de l'apprentissage. Mes amis sont fiers de moi, et honnêtement, je suis fière de moi-même aussi. On fête ça ce soir avec un gâteau et un bon verre de vin. Aux mille prochains mots. Santé ! Paris se sent déjà vraiment comme à la maison.",gloss:{"le verre":"the glass (of wine)"}},
];
