// Tusen — graderade minihistorier för nederländska som lär sig svenska.
// m = milstolpe (antal påbörjade ord) för upplåsning.
const STORIES_SV=[
{m:50,t:"Kaffe på morgonen",txt:"God morgon! Jag är i huset vid kanalen. Det är tidigt. Jag dricker kaffe med mjölk och äter bröd med ost. Min flickvän sover fortfarande. Staden är lugn och vacker. Idag ska jag till jobbet med cykeln. Vädret är bra. Vilken fin dag!",gloss:{"fortfarande":"nog / still","lugn":"rustig"}},
{m:100,t:"Fika",txt:"I Sverige har man fika. Det betyder kaffe och något sött, till exempel en kanelbulle. Idag går jag och min flickvän till ett kafé. Vi dricker kaffe och äter en bulle tillsammans. Det är inte bara mat, det är en paus i dagen. Vi pratar och skrattar. Min flickvän tycker om fika, hon säger att det liknar det nederländska ordet 'gezellig'. Kanske har hon rätt!",gloss:{"kanelbulle":"kaneelbroodje","en paus":"een pauze"}},
{m:150,t:"En kväll med familjen",txt:"Ikväll äter vi hos hennes föräldrar. Hennes mamma lagar soppa och hennes pappa gör middagen. Mormor är också där! Hon berättar om förr. Jag förstår inte allt, men jag lyssnar noga. Efter maten dricker vi kaffe och äter tårta. Klockan elva åker vi hem. I bilen säger min flickvän: din svenska blir bättre och bättre! Jag är glad.",gloss:{"berättar":"vertelt","noga":"goed / precies"}},
{m:200,t:"Nycklarna",txt:"Vilken dag! I morse hade jag ingen tid, och jag hittade inte mina nycklar. Jag tittade i köket, i rummet och på bordet. Ingenting! Jag ringde min flickvän. Hon skrattade och sa: titta i jackan! Och ja, där var de. Jag kom sent till jobbet, men det gör inget. Misstag hör till att lära sig, särskilt på en måndag.",gloss:{"i morse":"vanochtend","hör till":"hoort bij"}},
{m:250,t:"Söndag i parken",txt:"Det är söndag och solen skiner. Vi promenerar tillsammans ett varv genom parken. Många människor tränar, barn leker, och hundar springer glada i gräset. Vi sitter på en bänk och äter glass. Min flickvän tar ett foto av mig. Jag skickar fotot till min syster i Nederländerna. Hon svarar direkt: vad fint! Kommer du snart på besök? Kanske i december, skriver jag. Jag saknar henne ibland.",gloss:{"ett varv":"een rondje","gräset":"het gras"}},
{m:300,t:"Besök från Nederländerna",txt:"Min syster kommer på besök! Hennes flyg landar klockan tio. Jag väntar på stationen med blommor. Där är hon! Vi pratar nederländska och det känns skönt. Jag visar henne stan: kanalerna, marknaden, och naturligtvis mitt favoritkafé. Hon tycker Amsterdam är underbart. På kvällen lagar vi mat tillsammans med min flickvän. Hon försöker prata nederländska och vi måste skratta så mycket. Vilken mysig vecka det här blir!",gloss:{"landar":"landt","naturligtvis":"natuurlijk"}},
{m:350,t:"Regn, regn, regn",txt:"Det har regnat i tre dagar. Vinden är stark och mitt paraply är trasigt. Jag cyklar till jobbet och blir helt blöt. Min kollega skrattar: välkommen till Nederländerna, fast tvärtom! Inne dricker jag varmt te. Efter jobbet går jag hem. Min flickvän har lagat soppa och lamporna är tända. Vi stannar inne och ser en film i soffan. Ute regnar det, men inne är det varmt och mysigt. Kanske är hösten inte så dålig ändå.",gloss:{"tvärtom":"andersom","tända":"aangestoken"}},
{m:400,t:"Att laga mat med hennes mamma",txt:"Idag lär jag mig laga mat av hennes mamma. Vi gör soppa med grönsaker: potatis, lök och tomater. Jag skär löken och måste gråta. Hon skrattar och ger mig ett glas vatten. Soppan luktar underbart. Vi äter tillsammans med färskt bröd och smör. Smaklig måltid, säger alla. Soppan är lite för salt, men ingen säger något. Efter maten får jag receptet med mig. Nästa vecka lagar jag det själv!",gloss:{"receptet":"het recept","lite":"een beetje"}},
{m:450,t:"Den nya jackan",txt:"Vintern kommer och jag behöver en varm jacka. I affären provar jag en blå jacka. För liten! Kvinnan i affären hämtar en annan storlek. Den här passar bra och den är inte dyr. Jag köper också en halsduk och varma sockor. Vid kassan betalar jag med kort. Ute är det kallt, men min nya jacka är skönt varm. Redo för vintern!",gloss:{"redo":"klaar"}},
{m:500,t:"Ett brev från kommunen",txt:"Det ligger ett brev från kommunen på bordet. Jag måste fylla i ett formulär för mitt pass. Formuläret är på nederländska och ganska svårt. Min flickvän hjälper mig. Vad betyder det här ordet, frågar jag. Hon förklarar allt. Efter en timme är vi klara. Det ordnar sig, säger hon. Nästa dag lämnar jag formuläret till kommunhuset. Kvinnan där är trevlig och pratar långsamt med mig. Allt är ordnat. Vad stolt jag är över mig själv!",gloss:{"ordnat":"geregeld","själv":"mezelf"}},
{m:550,t:"Sjuk hemma",txt:"Jag mår inte bra. Jag har ont i huvudet och feber. Jag stannar hemma i sängen. Min flickvän ringer husläkaren och hämtar medicin på apoteket. Hon kokar te och lagar soppa åt mig. Vad snällt! Jag sover nästan hela dagen. Katten ligger bredvid mig i sängen. Efter tre dagar mår jag bättre. Krya på dig funkar bäst med mycket sömn, te, och en snäll flickvän.",gloss:{"bäst":"het beste","sömn":"slaap"}},
{m:600,t:"Midsommar",txt:"Idag är det midsommar och vi firar tillsammans med min familj i Sverige. Alla bär blommor i håret. Vi dansar runt midsommarstången och sjunger gamla sånger. Min flickvän lär sig dansa 'små grodorna' och skrattar hela tiden. Vi äter sill, potatis och jordgubbar med grädde. På kvällen sitter vi ute och pratar länge, för det blir aldrig riktigt mörkt. Det här är min flickväns första midsommar, säger jag till min mamma. Säkert inte den sista, svarar hon. Skål, för sommaren!",gloss:{"midsommarstången":"de midzomerpaal","jordgubbar":"aardbeien","grädde":"slagroom"}},
{m:650,t:"Diskussionen",txt:"Vid middagen har vi en diskussion. Enligt mig är vintern vackrare i Sverige än här. Min flickvän håller inte med. Här kan man ibland åka skridskor på kanalerna, säger hon. Det stämmer, säger jag, men i Sverige har vi riktig snö och mer ljus på sommaren. Vi jämför de två länderna hela kvällen. Egentligen har vi båda rätt: båda länderna är underbara. Därför åker vi till Sverige i februari och stannar här i december.",gloss:{"diskussionen":"de discussie","ljus":"licht"}},
{m:700,t:"Kär i Amsterdam",txt:"Idag frågade min mamma: var träffades ni egentligen? Jag berättade historien. För två år sedan var min flickvän på semester i Amsterdam. På ett litet kafé runt hörnet bad hon om kaffe på engelska. Jag stod bakom henne och sa något roligt. Vi pratade hela eftermiddagen. Jag blev kär direkt, men också blyg. Efter semestern ringde vi varje helg. Ett år senare flyttade jag. Ibland ändras livet plötsligt, och det är underbart.",gloss:{"sedan":"geleden","ringde":"belden"}},
{m:750,t:"Punkteringen",txt:"Vilken dag! I morse hade min cykel en punktering. Naturligtvis regnade det också. Jag var tvungen att gå till jobbet och kom sent till mötet. Min kollega skrattade: det är verkligen nederländskt väder idag! Efter jobbet lagade min flickvän däcket. Hon kan det verkligen bra. Som tack köpte jag bitterballen till drinken. Slut gott, allt gott: vi satt tillsammans i soffan, varma och torra, med en öl.",gloss:{"tvungen":"gedwongen","slut gott, allt gott":"eind goed, al goed"}},
{m:800,t:"Lucia",txt:"Den trettonde december firar vi Lucia. Tidigt på morgonen sjunger barnen sånger med ljus i håret. Min flickvän hade aldrig sett det förut och blev helt tyst av förvåning. Vi äter lussekatter och pepparkakor och dricker glögg. Det är mörkt ute, men ljusen gör allt varmt och mysigt. Min flickvän säger: det här är den vackraste svenska traditionen jag har sett. Kanske firar vi det i Amsterdam nästa år också, med hennes familj.",gloss:{"lussekatter":"saffraanbroodjes","pepparkakor":"kruidige koekjes","glögg":"glühwein"}},
{m:850,t:"En dag borta",txt:"Vi tog båda en ledig dag och åkte tåg till Haarlem. Ingen rusningstid, ingen försening: allt gick bra. I Haarlem promenerade vi genom centrum och åt lunch på en uteservering. Sedan ett varv genom museet. På vägen hem träffade vi av en slump hennes gamla kollega på tåget. Liten värld! Hemma beställde vi mat, för att laga mat efter en sådan dag? Ingen lust. Det var en perfekt dag, ärligt talat.",gloss:{"liten värld":"kleine wereld","en sådan":"zo'n"}},
{m:900,t:"Missförståndet",txt:"Idag tog jag fel, och hur! Jag hade tid hos frisören klockan tio. Trodde jag. Men tiden var klockan halv tio, och på nederländska betyder halv tio alltså nio och trettio! Jag kom en halvtimme sent. Lyckligtvis var frisören trevlig och hade tid kvar. Alla gör det misstaget, sa hon, särskilt personer från utlandet. Nåväl, på svenska funkar det precis tvärtom, så egentligen har jag ingen ursäkt. Dumt av mig! Men mitt hår ser bra ut nu.",gloss:{"missförståndet":"het misverstand","nåväl":"nou ja","ursäkt":"excuus"}},
{m:950,t:"Besök av mamma",txt:"Min mamma bor hos oss den här veckan. Gästsängen står i vardagsrummet och huset är fullt. Igår visade jag henne stan: gavlarna vid kanalen, blommarknaden, och naturligtvis vårt favoritställe vid vattnet. Hon tyckte allt var underbart, men de smala trapporna tyckte hon var farliga! Ikväll lagar min flickvän mat till oss. Hon är nervös, för min mamma är ärlig om mat. Men det blir säkert mysigt. Två språk vid ett bord, och alla förstår varandra ändå.",gloss:{"säkert":"vast"}},
{m:1000,t:"Tusen ord",txt:"Idag är det äntligen dags: jag kan tusen svenska ord! När jag började kunde jag bara säga hej och tack så mycket. Nu pratar jag med grannarna, beställer utan problem på uteserveringen, och förstår samtalen vid middagen. Naturligtvis gör jag fortfarande fel, men att göra fel hör till att lära sig. Min flickvän är stolt över mig, och ärligt talat är jag också stolt över mig själv. Vi firar det ikväll med tårta och ett gott glas vin. Skål för de nästa tusen orden. Amsterdam känns nu verkligen som hemma.",gloss:{"dags":"zover","själv":"mezelf"}},
];
